class CommonConstants {}

//ACTIONS
CommonConstants.ACTION_OPEN_CLOSE_APP_LEFT_DRAWER = 'ACTION_OPEN_CLOSE_APP_LEFT_DRAWER';
CommonConstants.ACTION_SHOW_MESSAGE_TO_USER = 'ACTION_SHOW_MESSAGE_TO_USER';

//EVENTS
CommonConstants.EVENT_OPEN_CLOSE_APP_LEFT_DRAWER = 'EVENT_OPEN_CLOSE_APP_LEFT_DRAWER';
CommonConstants.EVENT_SHOW_MESSAGE_TO_USER = 'EVENT_SHOW_MESSAGE_TO_USER';

export default CommonConstants;